### ISSUE TITLE
Fix the reference docs

### ISSUE THREAD

**Issue by pgjones** [pallets/quart#164]
They aren't being shown https://quart.palletsprojects.com/en/latest/reference/api.html

**Comment by mmdbalkhi** [comment]
hi @pgjones, can I work on it?

**Comment by pgjones** [comment]
Sure, this is the local command https://github.com/pallets/quart/blob/main/tox.ini#L32 - I think the only issue is that it isn't clear how to run that with Read the docs - or whether it should be run beforehand and committed to the repo.

I'm not sure what Flask does, but that might also be a solution.

**Comment by mmdbalkhi** [comment]
> I'm not sure what Flask does, but that might also be a solution.

I almost want to use Flask's texts, can I use them?

The problem is probably because there used to be a file `docs/reference/source`, it was working locally, but the `source/` is in Sphinx's gitignore and can't commit files in the `docs/source/`.

![image](https://user-images.githubusercontent.com/65954744/181046863-e42e4df5-06ad-45ec-8ddf-11e4dde854f2.png)

**Comment by pgjones** [comment]
I think `sphinx-apidoc -e -f -o docs/reference/source/ src/quart/` creates the file from the current source code. If so I think we need a way to run this as part of the docs build. 

Unless the issue is that that file needs to be created manually?

**Comment by mmdbalkhi** [comment]
I don't think there is much difference in principle. so Supposedly, if a new module is added in the future, it can be added manually::

```rst
.. automodule:: foo
```

```rst
.. autoclass:: Boo
```

I think Flask use this method,  Of course, it better if a single file could be created automatically not many files. what do you think?
