### ISSUE TITLE
Cannot Instantiate `Quart` object with `Flask==3.1.0`

### ISSUE THREAD

**Issue by biniona** [pallets/quart#371]
Unable to instantiate `Quart` object with `Flask==3.1.0`.

Run the following code from terminal:

```
pip install quart
```

Run the following code:

```python
from quart import Quart

Quart(__name__)
```

Outputs the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.pyenv/lib/python3.11/site-packages/quart/app.py", line 338, in __init__
    self.add_url_rule(
  File ".../.pyenv/lib/python3.11/site-packages/flask/sansio/scaffold.py", line 47, in wrapper_func
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.pyenv/lib/python3.11/site-packages/flask/sansio/app.py", line 641, in add_url_rule
    if "OPTIONS" not in methods and self.config["PROVIDE_AUTOMATIC_OPTIONS"]:
                                    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'PROVIDE_AUTOMATIC_OPTIONS'
```

Output of `pip freeze`:

```
aiofiles==24.1.0
blinker==1.9.0
click==8.1.7
Flask==3.1.0
h11==0.14.0
h2==4.1.0
hpack==4.0.0
Hypercorn==0.17.3
hyperframe==6.0.1
itsdangerous==2.2.0
Jinja2==3.1.4
MarkupSafe==3.0.2
priority==2.0.0
Quart==0.19.8
Werkzeug==3.1.3
wsproto==1.2.0
```

Installing `Flask==3.0.0` fixes the issue:

The expected behavior is a successful instantiation of a `Quart` object.

Environment:

- Python version: `3.11.3`
- Flask version: `3.1.0`

**Comment by JamesParrott** [comment]
Ths missing key was added after Flask 3.0.0, by the time 3.1.0 as would be expected.  It appears in a hardcoded dict of defaults:
https://github.com/pallets/flask/blame/bc098406af9537aacc436cb2ea777fbc9ff4c5aa/src/flask/app.py#L208

There's a separate hard coded dict in Quart (the defaults in sansio/app.py are empty) which has not been updated to be compatible with Flask 3.1.0.

](https://github.com/pallets/quart/blob/ef23e8b063ee0b1ae95ba5828570552685ad89bb/src/quart/app.py#L229C5-L229C20)

PROVIDE_AUTOMATIC_OPTIONS is not the only missing key in Quart.  If Quart intends to be compatible with Flask, is there any reason quart.app.Quart.default_config can't use Flask's defaults Flask, and override which ever ones it needs to?  

Otherwise in future, Quart will inevitably encounter similar issues to this one, just with some other missing key, the next time Flask adds a new setting, as its hardcoded dict must manually be kept current with Flask's, which is sub-optimal in terms of all our valuable developer time, to say the least.

**Comment by mikeckennedy** [comment]
Hi all, I'm getting the same issue but with a much simpler code base:

```
pip install quart
```

then

```python
import quart
app = quart.Quart(__name__)
print("Success")
```

Then I get the exception for KeyError as well. It's not a matter of compatibility with Flask directly. It's just broken with the latest update to Flask which comes along for the ride.

**Comment by JamesParrott** [comment]
This issue (along with many others) is fixed by PR #374

**Comment by speedpetr** [comment]
I solved this issue by these two lines, if you don't need static_folder:
app = Quart(__name__, static_folder=None)
app.config["PROVIDE_AUTOMATIC_OPTIONS"] = True

**Comment by JamesParrott** [comment]
> I solved this issue by these two lines, if you don't need static_folder: app = Quart(**name**, static_folder=None) app.config["PROVIDE_AUTOMATIC_OPTIONS"] = True

If you're happy to manually set this, and all the missing configuration variables, that's fine.

But Quart should really work out of the box, with minimal configuration required.

**Comment by develerltd** [comment]
shouldn't something be raised in flask's issues - as this should have  been a minor change (3.0.x to 3.1.0) but resulted in a breaking change?

**Comment by marcospgp** [comment]
there is a flask >= 3.0.0 dependency in the Quart dependency list, with no associated lockfile, so this issue showed up even without a new Quart release. this should be addressed by appropriately pinning quart's dependencies and checking a lockfile into the repo

**Comment by davidism** [comment]
There is a PR open for this, and we are working on a release, which will be out soon. Pinning the dependency in Quart is not the answer (see below), fixing the bug is.

---

When writing an application, you _must_ use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your application's full dependency tree. This gives you reproducible deployments, allowing you to control when you get updates.

Please review any of the following for more information:

* https://hynek.me/articles/semver-will-not-save-you/
* https://www.youtube.com/watch?v=WSVFw-3ssXM&t
* https://snarky.ca/why-i-dont-like-semver/
* https://caremad.io/posts/2016/02/versioning-software/
* https://bernat.tech/posts/version-numbers/
* https://iscinumpy.dev/post/bound-version-constraints/

**Comment by davidism** [comment]
Yes, it's a bit unintuitive, but limiting max versions in libraries has undesirable effects, as explained in the linked blogs. Pinning in your application means your builds are reproducible until you choose to upgrade, at which point you see tests fail, report bugs, but don't upgrade until they're fixed.

**Comment by develerltd** [comment]
the implication of this is that this version of quart that is currently released (and any older version of quart from when it used flask>=3.0.0) is now unusable by means of the change in flask

**Comment by davidism** [comment]
Quart 0.19.9 is now available on PyPI.
